# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

firstZeroIndex <- function(mat) {
    .Call(`_bunsen_firstZeroIndex`, mat)
}

rbinom_matrix_vec <- function(nrows, ncols, probs) {
    .Call(`_bunsen_rbinom_matrix_vec`, nrows, ncols, probs)
}

